### ISSUE TITLE
Access Key/Secret Key: cannot find symbol variable

### ISSUE THREAD

**Issue by monika1800** [visenze/visearch-sdk-android#22]
Please help with this. What should be done to make the program run successfully. How to set up the access key and secret key? Reply as soon as possible.

**Comment by yulu** [comment]
Hi, you can find the step to step setup guide here: http://developers.visenze.com/guides/android/index.html#Run-the-Demo
If you do not have a key pair yet, you need to register an account and prepare your data. Please follow the guide here:http://developers.visenze.com/setup/#Create-Your-First-App
