### ISSUE TITLE
MyActivity.java file not found in the Project

### ISSUE THREAD

**Issue by monika1800** [visenze/visearch-sdk-android#23]
I am not able to find MyActivity.java in the project which I think is an important file which is to be there. Also the entry of the activity is not traced in AndroidManifest.xml. If this Activity is to created manually then please guide me with the location at which the Activity should be made along with the content to be coded for reference purpose.

**Comment by yulu** [comment]
The entry is 'MainActivity.java' instead of MyActivity. The project is built in such a way that you can just import and run.
