### ISSUE TITLE
Showing Invalid Access Key or Secreet Key

### ISSUE THREAD

**Issue by alikazmi181293** [visenze/visearch-sdk-android#46]
I need a solution for that when ever i tried to pick photo from galary to analyze it... it says Invalid Access key or Secreet Key

**Comment by yulu** [comment]
please make sure you get a valid key pair from visenze before you try out the demo

**Comment by waqarmkhani** [comment]
Do you have a testing Access key

**Comment by yulu** [comment]
This android SDK works only with a valid visenze account, please refer to our developer site for more information: https://developers.visenze.com/. I will close this issue for now.
