### ISSUE TITLE
Chinese characters are lost when uploading image byte array

### ISSUE THREAD

**Issue by timemanx** [visenze/visearch-sdk-android#52]
When using `UploadSearchParams` with `Image` and `fq` containing Chinese characters, the Chinese characters are lost.

It's because `MultiPartRequest` doesn't set any content type when adding to `MultipartEntityBuilder` which in turn sets the default content type `ContentType#TEXT_PLAIN` which has ISO_8859_1 charset.

<img src="https://user-images.githubusercontent.com/1146030/47844002-9c668500-de04-11e8-952a-2108ec33c2af.jpg" width=400/>

**Comment by Shebella** [comment]
Same as @shubhadeepc

**Comment by william30101** [comment]
Encountered the same problem.
